@startuml
skinparam backgroundColor #FFFFFF
skinparam classAttributeIconSize 0

interface ConnectIntf {
    + watch_events() : void
    + send(clientId : string, data : span<char>) : bool
    + receive(socket : int) : MqttPacketContext
}

interface DbIntf {
    + get_session(clientId : string) : shared_ptr<ClientSession>
    + save_session(session : ClientSession) : void
    + get_pending_store() : PendingMessageStore&
}

interface ThreadPoolIntf {
    + enqueue(task : function<void()>) : void
}

struct MqttPacketContext {
    + raw_data : shared_ptr<vector<char>>
    + clientId : string
    + socket_fd : int
}

class ClientQueue {
    - mtx : std::mutex
    - cv : std::condition_variable
    - messages : std::queue<MqttPacketContext>
    + push(msg : MqttPacketContext) : void
    + pop_wait() : MqttPacketContext
}

class ClientSession {
    + clientId : string
    + socket_fd : int
    + queue : ClientQueue
    + subscriptions : vector<Subscription>
}

class DbMgr {
    - sessions : std::unordered_map<string, shared_ptr<ClientSession>>
    - sessions_mtx : std::shared_mutex
    + get_session(clientId) : shared_ptr<ClientSession>
}

class WorkerPool {
    - workers : vector<jthread>
    - task_queue : Queue<function<void()>>
    + enqueue(task) : void
}

class OutboundPool {
    - workers : vector<jthread>
    + watch_session(clientId : string) : void
}

class MqttListener {
    - connectMgr : ConnectIntf
    - workerPool : ThreadPoolIntf
    - dbMgr : DbIntf
    + run_loop() // Usa epoll_wait / watch_events
}

class MqttProtocolHandler {
    + static handle(context : MqttPacketContext, db : DbIntf) : void
}

' Relações
Main *-- ConnectMgr
Main *-- WorkerPool
Main *-- OutboundPool
Main *-- DbMgr
Main *-- MqttListener

ConnectMgr ..|> ConnectIntf
DbMgr ..|> DbIntf
WorkerPool ..|> ThreadPoolIntf
OutboundPool ..|> ThreadPoolIntf

MqttListener --> ConnectIntf : listen
MqttListener --> WorkerPool : dispatch task
WorkerPool ..> MqttProtocolHandler : invoke
MqttProtocolHandler --> DbIntf : update state
DbIntf o-- ClientSession
ClientSession *-- ClientQueue
OutboundPool --> DbIntf : monitor queues
OutboundPool --> ConnectIntf : send data

@enduml